server:
  port: 8080

spring:
  application:
    name: smartload-optimization-api

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
